PROGRAM=wlSyncS
LIBNETDIR=../
OBJS=main.o param.o
SRCS=$(OBJS:%.o=%.c)
CFLAGS=-Wall -g -I$(LIBNETDIR)/libnetMT/
LDFLAGS=-L$(LIBNETDIR)/libnetMT/
LDLIBS=-lnet -lpthread
$(PROGRAM):$(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(PROGRAM) $(OBJS) $(LDLIBS)
